run:
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    timeout: 5m

    # include test files or not, default is true
    tests: false

linters:
    enable:
        - asciicheck
        - bodyclose
        - cyclop
        - dogsled
        - durationcheck
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - forbidigo
        - forcetypeassert
        - funlen
        - gci
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - goerr113
        - goprintffuncname
        - gosec
        - ifshort
        - importas
        - makezero
        - misspell
        - nakedret
        - nestif
        - nilerr
        - nlreturn
        - noctx
        - nolintlint
        - paralleltest
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - exportloopref
        - sqlclosecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - wastedassign
        - whitespace
        - wsl

linters-settings:
    wsl:
        enforce-err-cuddling: true
    gocognit:
        # minimal code complexity to report, 30 by default (but we recommend 10-20)
        min-complexity: 20
    cyclop:
        max-complexity: 15
    funlen:
        lines: 80
    errcheck:
        exclude: .golangci_errcheck_exclude.txt
issues:
    # Disable default exclusion (otherwise most of golint issues are not catched)
    exclude-use-default: false
