FROM golang:1.17 as deps

WORKDIR /go/src

RUN go install github.com/cespare/reflex@latest

FROM deps as app

COPY cmd cmd
COPY pkg pkg

COPY go.mod ./
COPY go.sum ./

ENTRYPOINT reflex -s -r '\.go$' go run cmd/sellerpayout/sellerpayout.go --decoration=none